// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/graylock-navs/OutcomeLed.tsx": () => import("../components/mockups/graylock-navs/OutcomeLed.tsx"),
  "./components/mockups/graylock-navs/ServicesIndustries.tsx": () => import("../components/mockups/graylock-navs/ServicesIndustries.tsx"),
  "./components/mockups/graylock-navs/SolutionsHub.tsx": () => import("../components/mockups/graylock-navs/SolutionsHub.tsx")
};
