// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-intro/LandingIntro.tsx": () => import("../components/mockups/landing-intro/LandingIntro.tsx"),
  "./components/mockups/landing-intro-variant/LandingIntroVariant.tsx": () => import("../components/mockups/landing-intro-variant/LandingIntroVariant.tsx")
};
